#!/bin/sh

set -e

color=000000

if [ "${SWAYSOCK}" ]; then
    capture="grim"
    lock="swaylock -f"
    quit="swaymsg exit"
else
    capture="scrot"
    lock="i3lock"
    quit="i3-msg exit"
fi

lock() {
    if command -v $capture > /dev/null && command -v convert > /dev/null; then
        umask 0177
        IMAGE_FILE=$(mktemp --tmpdir .${USER}-screenlock.XXXX.png)
        trap 'rm -f -- "${IMAGE_FILE}"' INT TERM HUP EXIT

        # Delay added to remove locking artifacts
        sleep 0.05

        $capture ${IMAGE_FILE}
        convert -scale 5% -scale 2000% ${IMAGE_FILE} ${IMAGE_FILE}
        $lock -c $color -i ${IMAGE_FILE}
    else
        $lock -c $color
    fi
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        $quit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
